services:
  app:
    image: huecester/gamercenter
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGUSER: pguser
      PGPASSWORD: postgres
      PGDATABASE: gamercenter

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamercenter
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
